#!/bin/bash

module="mailslot"
device="mailslot"

# Invoke rmmod with all provided arguments.
/sbin/rmmod $module

# Remove stale nodes.

rm /dev/${device}*
#rm -f /dev/${device}priv
#rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
#rm -f /dev/${device}single
#rm -f /dev/${device}uid
#rm -f /dev/${device}wuid
