# Comment/uncomment the following line to disable/enable debugging
DEBUG = n

# Add your debudefgging flag (or not) to ccflags.
ifeq ($(DEBUG),y)
  DEBFLAGS = -O -g -DMAILSLOT_DEBUG # "-O" is needed to expand inlines
else
  DEBFLAGS = -O2
endif

ccflags-y += $(DEBFLAGS)
ccflags-y += -I$(LDDINC)

ifneq ($(KERNELRELEASE),)
# call from kernel build system

mailslot-objs := main.o read.o write.o ioctl.o mm/main_mm.o
#mailslot-objs := main.o read.o write.o ioctl.o mm/vmalloc_mm.o


obj-m	:= mailslot.o

else

KERNELDIR ?= /lib/modules/$(shell uname -r)/build
PWD       := $(shell pwd)

modules:
	$(MAKE) -C $(KERNELDIR) M=$(PWD) LDDINC=$(PWD)/../include modules

endif


clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions

depend .depend dep:
	$(CC) -M *.c > .depend


ifeq (.depend,$(wildcard .depend))
include .depend
endif



#***********************************************************************************
# TEST CASES
#***********************************************************************************
# N.B.: errors generated by 'diff' are ignored in order to allow the module unload.

test: pretest testFIFO testReadBlock posttest

pretest:
	@echo "loading the module"
	sudo ./mailslot_load

testFIFO: testDir=./test/testFIFO
testFIFO:
	@echo "*************************testFIFO*************************"
	gcc $(testDir)/test.c -o $(testDir)/test -lpthread
	$(testDir)/test 1 < $(testDir)/in > $(testDir)/test_out
	-diff $(testDir)/out $(testDir)/test_out
	@echo "************************* Done *************************"


testReadBlock: testDir=./test/testReadBlock
testReadBlock:
	@echo "*************************testReadBlock*************************"
	gcc $(testDir)/test.c -o $(testDir)/test -lpthread
	$(testDir)/test 1 < $(testDir)/in > $(testDir)/test_out
	-diff $(testDir)/out $(testDir)/test_out
	@echo "************************* Done *************************"


posttest:
	@echo "unloading the module"
	sudo ./mailslot_unload
